# Generated by Django 6.1.1 on 2026-09-17 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mudanza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cliente_nombre",
                    models.CharField(max_length=150, verbose_name="Nombre del cliente"),
                ),
                (
                    "cliente_telefono",
                    models.CharField(max_length=30, verbose_name="Teléfono"),
                ),
                (
                    "cliente_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "direccion_origen",
                    models.CharField(
                        max_length=255, verbose_name="Dirección de origen"
                    ),
                ),
                (
                    "direccion_destino",
                    models.CharField(
                        max_length=255, verbose_name="Dirección de destino"
                    ),
                ),
                ("fecha_mudanza", models.DateField(verbose_name="Fecha de la mudanza")),
                (
                    "inventario",
                    models.TextField(
                        blank=True, verbose_name="Inventario / objetos a mover"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "firma_cliente",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nombre de quien firma"
                    ),
                ),
                (
                    "conforme",
                    models.BooleanField(
                        default=False, verbose_name="El cliente da su conformidad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("en_curso", "En curso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "mudanza",
                "verbose_name_plural": "mudanzas",
                "ordering": ["-fecha_mudanza", "-creado"],
            },
        ),
    ]
